#Github page settings
lsi: false
pygments: true
markdown: rdiscount

destination: ./_site

url: http://madewithloveinparis.org

author:
    name: Rémi Barbe
    github: remiii
    twitter: Remiii_

production_url: http://madewithloveinparis.org

#permalink: /blog/:year/:month/:day/:title
#relative_permalinks: no

